# Site settings
title: Dian Jiao
general_email: dj2526@columbia.edu
academic_email: 

description: > # this means to ignore newlines until "baseurl:"
  This is the Dian Jiao's homepage updated on Dec 25, 2022. I aim to have an update on my site at least twice per annum. 

baseurl: "/homepage" # the subpath of your site, e.g. /blog/

url: "https://d-jiao.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: d-jiao
linkedin_username: Dian Jiao
linkedin_url: "https://www.linkedin.com/in/dian-jiao-99b701103/"
facebook_username: 
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile